version: '3.8'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: